pool:
  vmImage: ubuntu-latest

steps:
- script: npm i playwright @cucumber/cucumber typescript ts-node @types/node -D
  displayName: 'setting-up an environment'

- script: |
    npm test
  displayName: 'running ui tests'
