# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

steps:
- script: npm i playwright @cucumber/cucumber typescript ts-node @types/node -D
  displayName: 'setting-up an environment'

- script: |
    npm test
  displayName: 'running ui tests'
